name: release-artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - name: Generate SBOM
        run: |
          pip install cyclonedx-bom
          cyclonedx-py environment --output-file sbom.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist-and-sbom
          path: |
            dist/*
            sbom.json

